name: Telegram Pull Request Notifier

on:
  pull_request:
    types: [opened, review_requested, closed, edited]
  pull_request_review_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_target:
    types: [opened, edited, closed, reopened, review_requested, review_request_removed]

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      # Send a telegram message on pr open or review request
      - name: Pull Request Telegram
        uses: F2had/pr-telegram-action@v1.0.0
        with: 
          bot_token: '${{ secrets.PRBOTTOKEN }}' # Your bot token from github secrets
          chat_id: '${{ secrets.PRCHATID }}' # Your chat id from github secrets
