name: Telegram Pull Request Notifier

on:
  pull_request:
    types: [opened, review_requested, closed, edited]
  push:

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Message to Telegram
        shell: pwsh
        run: |
            # Переменные для отправки в телегу
            $botToken = "7463441241:AAGN2_tjL8aJctKQ8p1CfjKW61GkA48u7Kg"
            $chatId = "-1002125306971"
            $messageText = "Hello World from PowerShell"
            $url="https://api.telegram.org/bot$botToken/sendMessage?chat_id=$chatID&text=$messageText"
            Invoke-RestMethod -Uri $url -Method Post
